version: 2

sphinx:
  configuration: docs/conf.py

formats:
  - htmlzip

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  commands:
    - pip install tox
    - tox -e docs -- _readthedocs/html/

python:
  install:
    - method: pip
      path: .
